version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - "postgres:/var/lib/postgresql/data"
    networks:
      - postgres
    restart: always
  pgadmin:
    links:
      - db:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /tmp/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
